### ISSUE TITLE
The Loss_G is still increasing while the Loss_D remaining stable

### ISSUE THREAD

**Issue by LIUFGUI** [LukasMosser/PorousMediaGan#10]
Hi,
I am sorry to trouble you, 
I want to reproduce the work: Reconstruction of Berea in your paper. The same parameters as yours I have used for training, but I have the strange results: the Loss_G keeps increasing, and the corresponding Loss_D was stable at 0.3.

Maybe you know, what I could have done wrong?And what parameters should I have to changes to solve this problem？
Thank you！

**Comment by LukasMosser** [comment]
Did you manage to solve the issue?

**Comment by LIUFGUI** [comment]
Yes，
I changed “real_label = 0.9, fake_label = 0” to "real_label = np.random.uniform(0.9, 1.2), fake_label = np.random.uniform(0, 0.3)", so that the results got better. And it was better when  less training images were used to train the network. I still don't know why they worked.
Thank you all the same!
