### ISSUE TITLE
Which version of python and cuda did you use?

### ISSUE THREAD

**Issue by TheRealMephisto** [LukasMosser/PorousMediaGan#3]
Hi,
there seems to be a problem with using newer versions of python (3.7) and cuda (9.2).
I get two errors:
One complaining about nn.Container beeing deprecated, telling me to subclass nn.Module instead.
And another one complaining about using a different target size torch.size([128]) than the input size torch.size([128],[1]).
I think using the right versions of python and cuda should solve the problem.
So please tell me which you'd used, I didn't find it anywhere on the project Page here on Github.
Greetings!

**Comment by LukasMosser** [comment]
Hi @TheRealMephisto!

I believe I used python 2.7 and cuda 8.0 for this.
The main issue here may be that I used an older version of Pytorch. 
It was very likely Pytorch 0.2. I do not have a version that runs on version 1.0 but I believe there shouldn't be too much effort in porting. Main parts being changing nn.Containers to nn.Module.
I hope this helps, let me know if you run into more issues!

**Comment by TheRealMephisto** [comment]
Thank you for your answer!
It worked for me with that versions, so I will leave it as it is for now.

**Comment by TheRealMephisto** [comment]
Hi @LukasMosser !

Can you give me some more precise advice on how to port the network to newer versions?
I'm not sure what exactly to do...

Thanks in Advance!

**Comment by LukasMosser** [comment]
Hi @TheRealMephisto 
Are you still working on this?

**Comment by TheRealMephisto** [comment]
Hi @LukasMosser ,
thank you for asking.
I'm currently not working on this.
