### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by atsamaei** [LukasMosser/PorousMediaGan#9]
Hi, 

When I try "luarocks install hdf5" during installation of the code package, it shows the following error. What gcc version are you using?

Thanks.

(porousmedia) at@ari-206-04:~$ luarocks install hdf5 --local
Installing https://rocks.moonscript.org/hdf5-2.0.0-1.src.rock...
Using https://rocks.moonscript.org/hdf5-2.0.0-1.src.rock... switching to 'build' mode
Warning: variable CFLAGS was not passed in build_variables
make[1]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-5772/lua-hdf5/gcc-lua'
make[2]: Entering directory '/tmp/luarocks_hdf5-2.0.0-1-5772/lua-hdf5/gcc-lua/gcc'
gcclua-config.h:1:24: fatal error: gcc-plugin.h: No such file or directory
compilation terminated.
gcc -c -o gcclua.o -I/usr/lib/gcc/x86_64-linux-gnu/5/plugin/include -fPIC  -O2 -Wall -Wformat-security -I/usr/include/lua5.1 gcclua.c
gcclua.c:7:24: fatal error: gcc-plugin.h: No such file or directory
compilation terminated.
Makefile:29: recipe for target 'gcclua.o' failed
make[2]: *** [gcclua.o] Error 1
make[2]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-5772/lua-hdf5/gcc-lua/gcc'
Makefile:38: recipe for target 'gcc' failed
make[1]: *** [gcc] Error 2
make[1]: Leaving directory '/tmp/luarocks_hdf5-2.0.0-1-5772/lua-hdf5/gcc-lua'
Makefile:44: recipe for target 'gcc-lua' failed
make: *** [gcc-lua] Error 2

Error: Build error: Failed building.

**Comment by LukasMosser** [comment]
Hi @atsamaei ,

I'm sorry but I do not have the version of gcc that I used back in the day.
